apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Rg6nzykTTi42JZv3vjsMRyOZKUI=,iv:iP6ppRYkZywSh67oVAkA/Oo7ZqKSV2s2gNU0oF0p890=,tag:mtqnoz5b1GNuGtvuqpLDfA==,type:str]
    api-key: ENC[AES256_GCM,data:W9V9mQq6sTOAqqKM7FBIAeNFU3byWG5updNAWekXp4FG5qfgBw==,iv:almHgf5V4HTJ3WaWlsadaYXfr1T6+fux7THvT2eTVMg=,tag:Lvz4nt+MBgLoug/iwH+r5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vf3lpxn7ff7nghesqm56g6jnvne82gps5ytplxxw62mg9wsy6pnqt0p4fr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla1VMeFFVM0JEQlRreU0w
            cEoxMUVmSXhIcWZUQ1JZNDdFVCsvSXBkanh3CjRTUnhhbkw3R1YwdjRIVktQOHhX
            b2NvbXo4Vy9VTFBRL0FJcGFzakNoZEEKLS0tIE1zTlEvRDZORU1HNTE2NCtqcndX
            YmpPRTExcmFyMUR1Uis3Z3Y4MUpiQzAKbFiujmauciJe6uIhlkKs612QZQXFrtdf
            36KkOvKBVCoF4AoxjNAc4A6Npzl7pMhbbZ0yJI4UgsfQHj1flh0bZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T21:44:03Z"
    mac: ENC[AES256_GCM,data:BoyHEI+s1b+/kncSEc4OLHpVuNZVXSVUZbzlvmgjAtstMQeeL7F8POOxY/45eN1fYT4zTIbNFSS4YELunOo7pqUSpEpFiYwhOrrOIEaLE+aqj2lEFtOpy3uJSfIE/MOjjJ9UsRnnkeOowFtCBPbxegP+h9qhP+4G3TkEQfctAe4=,iv:FCizbflpgt7L/PenhJ3B0hQSm7zAicq+Ya0QrEzsqtE=,tag:BLz7bSeXSEWojFiHLtqTOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
