apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:k8MN6JwZPU/ceiAOhPQACMceeNjPCglWiyl6u45bqd9oY11MHKMD5j74rniXGLZADCUeEIXmYIbQGlKp,iv:d6RF8kBmvnNR3ocl+rS3yenFvrJ7/+elANJMHuMEmFE=,tag:OZ/92xvMrMH92WIxnJCouw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vf3lpxn7ff7nghesqm56g6jnvne82gps5ytplxxw62mg9wsy6pnqt0p4fr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVmV1cHRVZE94NXA0L2dk
            TkhwSUp3WHo2WE5WT3hoMFIrM2R5Vm9MNDJJCmdYZ2N2cUxLN1lhZG5KQXVEVnZi
            em1pRFFTRktsallNeUNpYmN4R2FpYjgKLS0tIENSTlgvQ0Z5OFlBYm5zWUNxekZC
            b1l0MmVWeUppS2trUkEyUW9OWUJMelEKBM5I2iG6q1NuuEyn21yE48zWvu5tsUho
            Ga/vc3iintn41/HgJ7yqUnayqMIBsNWLyNZpJobl7sFbCzH7/SmUKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T21:44:04Z"
    mac: ENC[AES256_GCM,data:o1AgMSC1bh5rZ3Q/fnxRso8EgtfGt2mLJx3TSpwghTiH5jY/pmIX/x3Fm8G9x7Nvk6e2iyqWDcjmSSbCP9BMKWj7W/cPk4/v4vbcX9LVvdy5LEqiU62MNVdm0FcqNVqYAOkxH2B95kIaaVY7zFXcFQoeAca4mshuNGOmiL9Q3g8=,iv:tK5GlK4A192k0oldpMWSHGO1Y5mKA6SL0lLkBsQIa2Y=,tag:4LsXRKENPmFnQG4f9QSpPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
