---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  KUBE_VIP_ADDR: "192.168.78.210"
  METALLB_LB_RANGE: "192.168.78.211-192.168.78.220"
  METALLB_K8S_GATEWAY_ADDR: "192.168.78.211"
  METALLB_INGRESS_ADDR: "192.168.78.212"
